// cvregio-frontend/src/components/page-header/PageSubmenu.tsx
import * as React from 'react';
import { CSSTransition } from 'react-transition-group';
import Icon, { IconTypes } from '../base/Icon';
import SubmenuLink from './SubmenuLink';
import { MenuItem } from './PageHeader';

import './PageSubmenu.scss';

export interface PageSubmenuProps {
    className: string;
    isList: boolean;
    menuItem?: MenuItem;
}

interface PageSubmenuState {
    menuItem?: MenuItem;
    show: boolean;
}

// export interface PageSubmenuState {}

class PageSubmenu extends React.Component<PageSubmenuProps, PageSubmenuState> {
    readonly state: PageSubmenuState = {
        menuItem: this.props.menuItem,
        show: false,
    };

    componentDidUpdate(prevProps: PageSubmenuProps) {
        if (this.props.menuItem?.title !== prevProps.menuItem?.title) {
            if (this.props.menuItem) {
                this.setState({ show: true, menuItem: this.props.menuItem });
            } else {
                this.setState({ show: false });
            }
        }
    }

    public render() {
        const { className = '', isList } = this.props;
        const { show, menuItem } = this.state;
        const items = menuItem?.children?.map(item => {
            return (
                <li key={item.title} className="menu-list__item">
                    <SubmenuLink href={item.href} type="block">
                        {item.title}
                    </SubmenuLink>
                </li>
            );
        });
        return (
            <CSSTransition in={show} timeout={200} classNames="fade-from-top" unmountOnExit>
                <div
                    className={`page-submenu ${className} ${
                        isList ? 'page-submenu--list' : 'page-submenu--grid'
                    }`}
                >
                    <div className="page-submenu__info description-block">
                        <h2 className="description-block__header">{menuItem?.title}</h2>
                        <p className="description-block__text" />
                        <a href={menuItem?.href} className="button description-block__link">
                            <Icon icon={IconTypes.ArrowRight} />
                            Übersicht
                        </a>
                    </div>
                    <ul
                        className={`page-submenu__menu-list ${
                            !isList ? 'page-submenu__menu-list--grid' : ''
                        }`}
                    >
                        {items}
                    </ul>
                </div>
            </CSSTransition>
        );
    }
}

export default PageSubmenu;

// cv-frontend/src/components/PageSubmenu.vue
<template>
    <div
        class="page-submenu"
        :class="{ 'page-submenu--grid': !isList, 'page-submenu--list': isList }"
    >
        <div class="page-submenu__info description-block">
            <h2 class="description-block__header">{{ title }}</h2>
            <p class="description-block__text"></p>
            <!-- <Button>MyButton</Button> -->
            <a :href="href" class="button description-block__link">
                <base-icon icon="arrow-right" primary />Übersicht
            </a>
        </div>
        <ul class="page-submenu__menu-list" :class="{ 'page-submenu__menu-list--grid': !isList }">
            <li v-for="item in items" :key="item.title" class="menu-list__item">
                <submenu-link :href="item.href" type="block">{{ item.title }}</submenu-link>
            </li>
        </ul>
    </div>
</template>

<script>
import Vue from 'vue';
import SubmenuLink from './SubmenuLink.vue';

export default Vue.extend({
    components: {
        SubmenuLink,
    },
    props: {
        title: {
            type: String,
            required: true,
        },
        description: {
            type: String,
        },
        items: {
            type: Array,
            default: () => [],
        },
        href: {
            type: String,
            default: '',
        },
        isList: {
            type: Boolean,
            default: false,
        },
    },
});
</script>

<style lang="scss">
.page-submenu {
    background: #eee;
    padding: 20px 40px;

    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    font-family: 'Open Sans';
    position: absolute;
    padding-top: 100px;
    width: 100%;

    &--list {
        // height: calc(100vh - 75px);
        padding: 100px 20px 0 20px;
        flex-direction: column;
        align-items: flex-start;
        justify-content: flex-start;
    }
}

.description-block {
    &__header {
        font-weight: normal;
        font-style: italic;
        font-size: 1.2rem;
    }
}

.page-submenu__menu-list {
    list-style: none;
    max-height: 200px;
    padding: 0;
    width: 400px;
    display: flex;
    flex-direction: column;

    &--grid {
        margin-left: 40px;
        flex-wrap: wrap;
    }

    &__item {
        // width: 50%;
        flex: 1;
    }
}
</style>
