// cvregio-frontend/app/pages/Home.tsx
import * as React from 'react';
import '../../src/components/cetest/CetestElement';
import MyComponent from '../../src/components/MyComponent';
import MyWpComponent from '../../src/components/MyWpComponent';
import PageLayout from '../../src/layouts/PageLayout';
import Header from '../components/Header';
import Stage from '../components/Stage';

class Home extends React.Component {
    public render() {
        return (
            // <React.Fragment>
            <PageLayout
                header={<Header />}
                content={
                    <React.Fragment>
                        <article
                            id="post-78"
                            className="post-78 page type-page status-publish hentry entry"
                        >
                            <div className="entry-content entry-content--starting-top">
                                <Stage />
                                <h1>
                                    Willkommen beim <br />
                                    CVJM Stift Quernheim e.V.
                                </h1>
                                <p>
                                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                                    diam nonumy eirmod tempor invidunt ut labore et dolore magna
                                    aliquyam erat, sed diam voluptua. At vero eos et accusam et
                                    justo duo dolores et ea rebum.
                                </p>
                                <h2>Neuigkeiten</h2>
                                {/* <dev-news></dev-news> */}
                                {/* <cv-sidebar data-row-start="6" /> */}
                                <p>
                                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
                                    diam nonumy eirmod tempor invidunt ut labore et dolore magna
                                    aliquyam erat, sed diam voluptua. At vero eos et accusam et
                                    justo duo dolores et ea rebum.
                                </p>
                                <collapsible-panel name="asd" />
                            </div>
                        </article>
                        <MyComponent />
                        <MyWpComponent />
                    </React.Fragment>
                }
            />
            // </React.Fragment>
        );
    }
}

export default Home;

// cv-frontend/src/dev-pages/Home.vue
<template>
    <div>
        <dev-header></dev-header>
        <div id="content" class="site-content">
            <section id="primary" class="content-area">
                <main id="main" class="site-main">
                    <article
                        id="post-78"
                        class="post-78 page type-page status-publish hentry entry"
                    >
                        <div class="entry-content entry-content--starting-top">
                            <stage></stage>
                            <!-- <section class="wp-block-cv-blocks-cv-stage undefined alignfull"> -->
                            <h1>Willkommen beim <br />CVJM Stift Quernheim e.V.</h1>
                            <p>
                                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
                                nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
                                erat, sed diam voluptua. At vero eos et accusam et justo duo dolores
                                et ea rebum.
                            </p>
                            <h2>Neuigkeiten</h2>
                            <dev-news></dev-news>
                            <cv-sidebar :row-start="6" />
                            <p>
                                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
                                nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
                                erat, sed diam voluptua. At vero eos et accusam et justo duo dolores
                                et ea rebum.
                            </p>
                        </div>
                    </article>
                </main>
                <!-- #main -->
            </section>
            <!-- #primary -->
        </div>
    </div>
</template>

<script>
import stage from '../dev-components/stage.vue';
import DevHeader from '../dev-components/dev-header.vue';
import DevNews from '../dev-components/dev-news.vue';
import CvSidebar from '../static-components/cv-sidebar.vue';

export default {
    components: {
        stage,
        DevHeader,
        DevNews,
        CvSidebar,
    },
};
</script>

<style lang="scss">
#app {
    // font-family: 'Avenir', Helvetica, Arial, sans-serif;
    // -webkit-font-smoothing: antialiased;
    // -moz-osx-font-smoothing: grayscale;
    // text-align: center;
    // color: #2c3e50;
    // margin-top: 60px;
}
</style>
