// cv-frontend/src/static-components/info-row.vue
<template>
    <div class="info-row">
        <div class="info-row__header">
            <base-icon icon="edit" class="info-row__icon" size="12" />
            <span class="info-row__label">{{ label }}</span>
        </div>
        <div class="info-row__title">{{ title }}</div>
    </div>
</template>

<script>
export default {
    props: {
        label: {
            type: String,
            default: '',
        },
        title: {
            type: String,
            default: '',
        },
        iconName: {
            type: String,
            default: '',
        },
    },
};
</script>

// cvregio-frontend/src/components/groups/InfoRow.tsx
import * as React from 'react';
import Icon, { IconTypes } from '../base/Icon';

import './InfoRow.scss';

export interface InfoRowProps {
    label: string;
    title: string;
    icon?: IconTypes;
}

class InfoRow extends React.Component<InfoRowProps> {
    public render() {
        const { icon = IconTypes.ArrowRight, label, title } = this.props;
        return (
            <div className="info-row">
                <div className="info-row__header">
                    <Icon icon={icon} className="info-row__icon" size={12} />
                    <span className="info-row__label">{label}</span>
                </div>
                <div className="info-row__title">{title}</div>
            </div>
        );
    }
}

export default InfoRow;
